{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: base-node-rpc
  version: {{ GIT_VERSION }}

requirements:
  build:
    - arduino-rpc >=1.10
    # .. versionadded:: 0.38
    - asyncserial >=0.2
    # .. versionadded:: X.X.X
    - blinker
    - future
    # .. versionadded:: X.X.X
    - json-tricks >=3.8.0
    # .. versionadded:: 0.30
    # .. versionchanged:: 0.38
    - nadamq >=0.14
    - paver
    - pip
    - platformio-framework-arduinoavr
    - platformio-framework-arduinoteensy
    - platformio-helpers >=0.4
    - platformio-tool-avrdude >=1.60300.1
    - platformio-tool-scons
    - platformio-tool-teensy
    - platformio-toolchain-atmelavr >=1.40902.1
    - platformio-toolchain-gccarmnoneeabi
    - python 2.7*
    # .. versionchanged:: 0.38
    - serial-device >=0.9

  run:
    - arduino-rpc >=1.10
    # .. versionadded:: 0.38
    - asyncserial >=0.2
    # .. versionadded:: X.X.X
    - blinker
    # .. versionadded:: X.X.X
    - json-tricks >=3.8.0
    # .. versionadded:: 0.30
    # .. versionchanged:: 0.38
    - nadamq >=0.14
    - python 2.7*
    - platformio-helpers >=0.4
    - platformio-tool-avrdude
    - platformio-tool-scons
    - platformio-tool-teensy
    # .. versionchanged:: 0.38
    - serial-device >=0.9

test:
  imports:
    - base_node_rpc
    # .. versionadded:: X.X.X
    - base_node_rpc._version
    - base_node_rpc.async
    # .. versionadded:: X.X.X
    - base_node_rpc.bin.upload
    # .. versionadded:: X.X.X
    - base_node_rpc.bootloader_driver
    # .. versionadded:: X.X.X
    - base_node_rpc.intel_hex
    # .. versionadded:: X.X.X
    - base_node_rpc.node
    # .. versionadded:: X.X.X
    - base_node_rpc.protobuf
    # .. versionadded:: X.X.X
    - base_node_rpc.proxy
    # .. versionadded:: X.X.X
    - base_node_rpc.queue

about:
  home: https://github.com/wheeler-microfluidics/base-node-rpc
  license: MIT
