# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: base-node-rpc
{% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.post{{ GIT_DESCRIBE_NUMBER }}
{% else %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.0
{% endif %}

requirements:
  build:
    - arduino-rpc >=1.10
    # .. versionadded:: 0.38
    - asyncserial >=0.2
    - future
    # .. versionadded:: 0.30
    - nadamq >=0.14
    - paver
    - pip
    - platformio-framework-arduinoavr
    - platformio-framework-arduinoteensy
    - platformio-helpers >=0.4
    - platformio-tool-avrdude
    - platformio-tool-scons
    - platformio-tool-teensy
    - platformio-toolchain-atmelavr
    - platformio-toolchain-gccarmnoneeabi
    - python 2.7*
    - serial-device >=0.9

  run:
    - arduino-rpc >=1.10
    # .. versionadded:: 0.38
    - asyncserial >=0.2
    # .. versionadded:: 0.30
    - nadamq >=0.14
    - python 2.7*
    - platformio-helpers >=0.4
    - platformio-tool-avrdude
    - platformio-tool-scons
    - platformio-tool-teensy
    - serial-device >=0.9

about:
  home: https://github.com/wheeler-microfluidics/base-node-rpc
  license: MIT
